services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: emitenota_app
    restart: unless-stopped
    ports:
      - "2083:2083"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    networks:
      - emitenota_network

networks:
  emitenota_network:
    driver: bridge