version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: emitenota_app
    restart: unless-stopped
#    ports:
#      - "2083:2083"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    networks:
      - emitenota_network

  tunnel:
    # Conector da Cloudflare
    image: cloudflare/cloudflared:latest
    container_name: cloudflare_nfe_tunnel
    restart: always
    command: tunnel run
    environment:

      - TUNNEL_TOKEN=eyJhIjoiOTg0ZmJlNDkwZmVkNjNhZjE4ZDcxYWI5OWE5MTQyMWUiLCJ0IjoiOWNiYjVkNjUtMWI3ZC00MzYwLTg4MDktNzIxNmM0NjY1NDY4IiwicyI6Ill6Z3lOVEJpTjJVdFkyTmxOeTAwTlRZekxXSTRNamN0TnpSbE9UVXdPV05rWm1FNCJ9
    networks:
      - emitenota_network

networks:
  emitenota_network:
    driver: bridge