ServerName localhost

DocumentRoot "/var/www/html/emitenota/giusoft/src"
<Directory "/var/www/html/emitenota/giusoft/src">
    Options FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>

DirectoryIndex index.php index.html

# UI em /View (V maiúsculo)
Alias /View "/var/www/html/emitenota/giusoft/src/View"
<Directory "/var/www/html/emitenota/giusoft/src/View">
    Options FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>

ErrorLog /proc/self/fd/2
CustomLog /proc/self/fd/1 common
